# Generated by Django 3.1.4 on 2021-04-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
