# Generated by Django 3.1.4 on 2021-04-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidresource',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covidresource',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
