# Generated by Django 3.1.4 on 2021-04-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210423_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidresource',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='covidresource',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='covidresource',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='covidresource',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
